/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ReviewId = IDL.Text;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Slug = IDL.Text;
export const ArticleInput = IDL.Record({
  'metaDescription' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'isPublished' : IDL.Bool,
  'featuredImage' : ExternalBlob,
  'slug' : Slug,
  'author' : IDL.Text,
});
export const ArticleId = IDL.Text;
export const Timestamp = IDL.Int;
export const Article = IDL.Record({
  'id' : ArticleId,
  'metaDescription' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'isPublished' : IDL.Bool,
  'featuredImage' : ExternalBlob,
  'slug' : Slug,
  'publishedAt' : Timestamp,
  'author' : IDL.Text,
  'updatedAt' : Timestamp,
});
export const PropertyStatus = IDL.Variant({
  'active' : IDL.Null,
  'pending' : IDL.Null,
  'sold' : IDL.Null,
  'inactive' : IDL.Null,
});
export const PropertyType = IDL.Variant({
  'rental' : IDL.Null,
  'resale' : IDL.Null,
  'newProject' : IDL.Null,
  'sale' : IDL.Null,
  'plotLand' : IDL.Null,
});
export const PropertyInput = IDL.Record({
  'galleryImages' : IDL.Vec(ExternalBlob),
  'status' : PropertyStatus,
  'title' : IDL.Text,
  'propertyType' : PropertyType,
  'bedrooms' : IDL.Nat,
  'city' : IDL.Text,
  'overview' : IDL.Text,
  'slug' : Slug,
  'description' : IDL.Text,
  'amenities' : IDL.Vec(IDL.Text),
  'heroImage' : ExternalBlob,
  'isFeatured' : IDL.Bool,
  'address' : IDL.Text,
  'areaSqft' : IDL.Float64,
  'bathrooms' : IDL.Nat,
  'price' : IDL.Float64,
  'floorplans' : IDL.Vec(ExternalBlob),
});
export const PropertyId = IDL.Text;
export const Property = IDL.Record({
  'id' : PropertyId,
  'galleryImages' : IDL.Vec(ExternalBlob),
  'status' : PropertyStatus,
  'title' : IDL.Text,
  'propertyType' : PropertyType,
  'bedrooms' : IDL.Nat,
  'city' : IDL.Text,
  'createdAt' : Timestamp,
  'overview' : IDL.Text,
  'slug' : Slug,
  'description' : IDL.Text,
  'amenities' : IDL.Vec(IDL.Text),
  'heroImage' : ExternalBlob,
  'updatedAt' : Timestamp,
  'isFeatured' : IDL.Bool,
  'address' : IDL.Text,
  'areaSqft' : IDL.Float64,
  'bathrooms' : IDL.Nat,
  'price' : IDL.Float64,
  'floorplans' : IDL.Vec(ExternalBlob),
});
export const LeadId = IDL.Text;
export const Review = IDL.Record({
  'id' : ReviewId,
  'isApproved' : IDL.Bool,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'propertyId' : PropertyId,
  'email' : IDL.Text,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
});
export const ArticlePage = IDL.Record({
  'total' : IDL.Nat,
  'offset' : IDL.Nat,
  'limit' : IDL.Nat,
  'items' : IDL.Vec(Article),
});
export const InquiryType = IDL.Variant({
  'offer' : IDL.Null,
  'information' : IDL.Null,
  'general' : IDL.Null,
  'viewingRequest' : IDL.Null,
});
export const Lead = IDL.Record({
  'id' : LeadId,
  'inquiryType' : InquiryType,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'propertyTitle' : IDL.Opt(IDL.Text),
  'propertyId' : IDL.Opt(PropertyId),
  'isRead' : IDL.Bool,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const PropertyFilters = IDL.Record({
  'propertyType' : IDL.Opt(PropertyType),
  'offset' : IDL.Nat,
  'minBedrooms' : IDL.Opt(IDL.Nat),
  'limit' : IDL.Nat,
  'searchTerm' : IDL.Opt(IDL.Text),
  'priceMax' : IDL.Opt(IDL.Float64),
  'priceMin' : IDL.Opt(IDL.Float64),
});
export const PropertyPage = IDL.Record({
  'total' : IDL.Nat,
  'offset' : IDL.Nat,
  'limit' : IDL.Nat,
  'items' : IDL.Vec(Property),
});
export const LeadInput = IDL.Record({
  'inquiryType' : InquiryType,
  'name' : IDL.Text,
  'propertyTitle' : IDL.Opt(IDL.Text),
  'propertyId' : IDL.Opt(PropertyId),
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const ReviewInput = IDL.Record({
  'name' : IDL.Text,
  'propertyId' : PropertyId,
  'email' : IDL.Text,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'approveReview' : IDL.Func([ReviewId], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createArticle' : IDL.Func([ArticleInput], [Article], []),
  'createProperty' : IDL.Func([PropertyInput], [Property], []),
  'deleteArticle' : IDL.Func([ArticleId], [IDL.Bool], []),
  'deleteLead' : IDL.Func([LeadId], [IDL.Bool], []),
  'deleteProperty' : IDL.Func([PropertyId], [IDL.Bool], []),
  'deleteReview' : IDL.Func([ReviewId], [IDL.Bool], []),
  'getArticle' : IDL.Func([ArticleId], [IDL.Opt(Article)], ['query']),
  'getArticleBySlug' : IDL.Func([Slug], [IDL.Opt(Article)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFeaturedProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
  'getProperty' : IDL.Func([PropertyId], [IDL.Opt(Property)], ['query']),
  'getPropertyAverageRating' : IDL.Func([PropertyId], [IDL.Float64], ['query']),
  'getPropertyBySlug' : IDL.Func([Slug], [IDL.Opt(Property)], ['query']),
  'getRecentArticles' : IDL.Func([IDL.Nat], [IDL.Vec(Article)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllReviews' : IDL.Func([], [IDL.Vec(Review)], []),
  'listArticles' : IDL.Func([IDL.Nat, IDL.Nat], [ArticlePage], ['query']),
  'listLeads' : IDL.Func([], [IDL.Vec(Lead)], []),
  'listProperties' : IDL.Func([PropertyFilters], [PropertyPage], ['query']),
  'listReviewsByProperty' : IDL.Func(
      [PropertyId],
      [IDL.Vec(Review)],
      ['query'],
    ),
  'markLeadRead' : IDL.Func([LeadId], [IDL.Bool], []),
  'submitLead' : IDL.Func([LeadInput], [Lead], []),
  'submitReview' : IDL.Func([ReviewInput], [Review], []),
  'toggleFeatured' : IDL.Func([PropertyId], [IDL.Bool], []),
  'updateArticle' : IDL.Func([ArticleId, ArticleInput], [IDL.Opt(Article)], []),
  'updateProperty' : IDL.Func(
      [PropertyId, PropertyInput],
      [IDL.Opt(Property)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ReviewId = IDL.Text;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Slug = IDL.Text;
  const ArticleInput = IDL.Record({
    'metaDescription' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'isPublished' : IDL.Bool,
    'featuredImage' : ExternalBlob,
    'slug' : Slug,
    'author' : IDL.Text,
  });
  const ArticleId = IDL.Text;
  const Timestamp = IDL.Int;
  const Article = IDL.Record({
    'id' : ArticleId,
    'metaDescription' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'isPublished' : IDL.Bool,
    'featuredImage' : ExternalBlob,
    'slug' : Slug,
    'publishedAt' : Timestamp,
    'author' : IDL.Text,
    'updatedAt' : Timestamp,
  });
  const PropertyStatus = IDL.Variant({
    'active' : IDL.Null,
    'pending' : IDL.Null,
    'sold' : IDL.Null,
    'inactive' : IDL.Null,
  });
  const PropertyType = IDL.Variant({
    'rental' : IDL.Null,
    'resale' : IDL.Null,
    'newProject' : IDL.Null,
    'sale' : IDL.Null,
    'plotLand' : IDL.Null,
  });
  const PropertyInput = IDL.Record({
    'galleryImages' : IDL.Vec(ExternalBlob),
    'status' : PropertyStatus,
    'title' : IDL.Text,
    'propertyType' : PropertyType,
    'bedrooms' : IDL.Nat,
    'city' : IDL.Text,
    'overview' : IDL.Text,
    'slug' : Slug,
    'description' : IDL.Text,
    'amenities' : IDL.Vec(IDL.Text),
    'heroImage' : ExternalBlob,
    'isFeatured' : IDL.Bool,
    'address' : IDL.Text,
    'areaSqft' : IDL.Float64,
    'bathrooms' : IDL.Nat,
    'price' : IDL.Float64,
    'floorplans' : IDL.Vec(ExternalBlob),
  });
  const PropertyId = IDL.Text;
  const Property = IDL.Record({
    'id' : PropertyId,
    'galleryImages' : IDL.Vec(ExternalBlob),
    'status' : PropertyStatus,
    'title' : IDL.Text,
    'propertyType' : PropertyType,
    'bedrooms' : IDL.Nat,
    'city' : IDL.Text,
    'createdAt' : Timestamp,
    'overview' : IDL.Text,
    'slug' : Slug,
    'description' : IDL.Text,
    'amenities' : IDL.Vec(IDL.Text),
    'heroImage' : ExternalBlob,
    'updatedAt' : Timestamp,
    'isFeatured' : IDL.Bool,
    'address' : IDL.Text,
    'areaSqft' : IDL.Float64,
    'bathrooms' : IDL.Nat,
    'price' : IDL.Float64,
    'floorplans' : IDL.Vec(ExternalBlob),
  });
  const LeadId = IDL.Text;
  const Review = IDL.Record({
    'id' : ReviewId,
    'isApproved' : IDL.Bool,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'propertyId' : PropertyId,
    'email' : IDL.Text,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const ArticlePage = IDL.Record({
    'total' : IDL.Nat,
    'offset' : IDL.Nat,
    'limit' : IDL.Nat,
    'items' : IDL.Vec(Article),
  });
  const InquiryType = IDL.Variant({
    'offer' : IDL.Null,
    'information' : IDL.Null,
    'general' : IDL.Null,
    'viewingRequest' : IDL.Null,
  });
  const Lead = IDL.Record({
    'id' : LeadId,
    'inquiryType' : InquiryType,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'propertyTitle' : IDL.Opt(IDL.Text),
    'propertyId' : IDL.Opt(PropertyId),
    'isRead' : IDL.Bool,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const PropertyFilters = IDL.Record({
    'propertyType' : IDL.Opt(PropertyType),
    'offset' : IDL.Nat,
    'minBedrooms' : IDL.Opt(IDL.Nat),
    'limit' : IDL.Nat,
    'searchTerm' : IDL.Opt(IDL.Text),
    'priceMax' : IDL.Opt(IDL.Float64),
    'priceMin' : IDL.Opt(IDL.Float64),
  });
  const PropertyPage = IDL.Record({
    'total' : IDL.Nat,
    'offset' : IDL.Nat,
    'limit' : IDL.Nat,
    'items' : IDL.Vec(Property),
  });
  const LeadInput = IDL.Record({
    'inquiryType' : InquiryType,
    'name' : IDL.Text,
    'propertyTitle' : IDL.Opt(IDL.Text),
    'propertyId' : IDL.Opt(PropertyId),
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ReviewInput = IDL.Record({
    'name' : IDL.Text,
    'propertyId' : PropertyId,
    'email' : IDL.Text,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'approveReview' : IDL.Func([ReviewId], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createArticle' : IDL.Func([ArticleInput], [Article], []),
    'createProperty' : IDL.Func([PropertyInput], [Property], []),
    'deleteArticle' : IDL.Func([ArticleId], [IDL.Bool], []),
    'deleteLead' : IDL.Func([LeadId], [IDL.Bool], []),
    'deleteProperty' : IDL.Func([PropertyId], [IDL.Bool], []),
    'deleteReview' : IDL.Func([ReviewId], [IDL.Bool], []),
    'getArticle' : IDL.Func([ArticleId], [IDL.Opt(Article)], ['query']),
    'getArticleBySlug' : IDL.Func([Slug], [IDL.Opt(Article)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFeaturedProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
    'getProperty' : IDL.Func([PropertyId], [IDL.Opt(Property)], ['query']),
    'getPropertyAverageRating' : IDL.Func(
        [PropertyId],
        [IDL.Float64],
        ['query'],
      ),
    'getPropertyBySlug' : IDL.Func([Slug], [IDL.Opt(Property)], ['query']),
    'getRecentArticles' : IDL.Func([IDL.Nat], [IDL.Vec(Article)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllReviews' : IDL.Func([], [IDL.Vec(Review)], []),
    'listArticles' : IDL.Func([IDL.Nat, IDL.Nat], [ArticlePage], ['query']),
    'listLeads' : IDL.Func([], [IDL.Vec(Lead)], []),
    'listProperties' : IDL.Func([PropertyFilters], [PropertyPage], ['query']),
    'listReviewsByProperty' : IDL.Func(
        [PropertyId],
        [IDL.Vec(Review)],
        ['query'],
      ),
    'markLeadRead' : IDL.Func([LeadId], [IDL.Bool], []),
    'submitLead' : IDL.Func([LeadInput], [Lead], []),
    'submitReview' : IDL.Func([ReviewInput], [Review], []),
    'toggleFeatured' : IDL.Func([PropertyId], [IDL.Bool], []),
    'updateArticle' : IDL.Func(
        [ArticleId, ArticleInput],
        [IDL.Opt(Article)],
        [],
      ),
    'updateProperty' : IDL.Func(
        [PropertyId, PropertyInput],
        [IDL.Opt(Property)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };