/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Article {
  'id' : ArticleId,
  'metaDescription' : string,
  'title' : string,
  'content' : string,
  'isPublished' : boolean,
  'featuredImage' : ExternalBlob,
  'slug' : Slug,
  'publishedAt' : Timestamp,
  'author' : string,
  'updatedAt' : Timestamp,
}
export type ArticleId = string;
export interface ArticleInput {
  'metaDescription' : string,
  'title' : string,
  'content' : string,
  'isPublished' : boolean,
  'featuredImage' : ExternalBlob,
  'slug' : Slug,
  'author' : string,
}
export interface ArticlePage {
  'total' : bigint,
  'offset' : bigint,
  'limit' : bigint,
  'items' : Array<Article>,
}
export type ExternalBlob = Uint8Array;
export type InquiryType = { 'offer' : null } |
  { 'information' : null } |
  { 'general' : null } |
  { 'viewingRequest' : null };
export interface Lead {
  'id' : LeadId,
  'inquiryType' : InquiryType,
  'name' : string,
  'createdAt' : Timestamp,
  'propertyTitle' : [] | [string],
  'propertyId' : [] | [PropertyId],
  'isRead' : boolean,
  'email' : string,
  'message' : string,
  'phone' : string,
}
export type LeadId = string;
export interface LeadInput {
  'inquiryType' : InquiryType,
  'name' : string,
  'propertyTitle' : [] | [string],
  'propertyId' : [] | [PropertyId],
  'email' : string,
  'message' : string,
  'phone' : string,
}
export interface Property {
  'id' : PropertyId,
  'galleryImages' : Array<ExternalBlob>,
  'status' : PropertyStatus,
  'title' : string,
  'propertyType' : PropertyType,
  'bedrooms' : bigint,
  'city' : string,
  'createdAt' : Timestamp,
  'overview' : string,
  'slug' : Slug,
  'description' : string,
  'amenities' : Array<string>,
  'heroImage' : ExternalBlob,
  'updatedAt' : Timestamp,
  'isFeatured' : boolean,
  'address' : string,
  'areaSqft' : number,
  'bathrooms' : bigint,
  'price' : number,
  'floorplans' : Array<ExternalBlob>,
}
export interface PropertyFilters {
  'propertyType' : [] | [PropertyType],
  'offset' : bigint,
  'minBedrooms' : [] | [bigint],
  'limit' : bigint,
  'searchTerm' : [] | [string],
  'priceMax' : [] | [number],
  'priceMin' : [] | [number],
}
export type PropertyId = string;
export interface PropertyInput {
  'galleryImages' : Array<ExternalBlob>,
  'status' : PropertyStatus,
  'title' : string,
  'propertyType' : PropertyType,
  'bedrooms' : bigint,
  'city' : string,
  'overview' : string,
  'slug' : Slug,
  'description' : string,
  'amenities' : Array<string>,
  'heroImage' : ExternalBlob,
  'isFeatured' : boolean,
  'address' : string,
  'areaSqft' : number,
  'bathrooms' : bigint,
  'price' : number,
  'floorplans' : Array<ExternalBlob>,
}
export interface PropertyPage {
  'total' : bigint,
  'offset' : bigint,
  'limit' : bigint,
  'items' : Array<Property>,
}
export type PropertyStatus = { 'active' : null } |
  { 'pending' : null } |
  { 'sold' : null } |
  { 'inactive' : null };
export type PropertyType = { 'rental' : null } |
  { 'resale' : null } |
  { 'newProject' : null } |
  { 'sale' : null } |
  { 'plotLand' : null };
export interface Review {
  'id' : ReviewId,
  'isApproved' : boolean,
  'name' : string,
  'createdAt' : Timestamp,
  'propertyId' : PropertyId,
  'email' : string,
  'comment' : string,
  'rating' : bigint,
}
export type ReviewId = string;
export interface ReviewInput {
  'name' : string,
  'propertyId' : PropertyId,
  'email' : string,
  'comment' : string,
  'rating' : bigint,
}
export type Slug = string;
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'approveReview' : ActorMethod<[ReviewId], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createArticle' : ActorMethod<[ArticleInput], Article>,
  'createProperty' : ActorMethod<[PropertyInput], Property>,
  'deleteArticle' : ActorMethod<[ArticleId], boolean>,
  'deleteLead' : ActorMethod<[LeadId], boolean>,
  'deleteProperty' : ActorMethod<[PropertyId], boolean>,
  'deleteReview' : ActorMethod<[ReviewId], boolean>,
  'getArticle' : ActorMethod<[ArticleId], [] | [Article]>,
  'getArticleBySlug' : ActorMethod<[Slug], [] | [Article]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFeaturedProperties' : ActorMethod<[], Array<Property>>,
  'getProperty' : ActorMethod<[PropertyId], [] | [Property]>,
  'getPropertyAverageRating' : ActorMethod<[PropertyId], number>,
  'getPropertyBySlug' : ActorMethod<[Slug], [] | [Property]>,
  'getRecentArticles' : ActorMethod<[bigint], Array<Article>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllReviews' : ActorMethod<[], Array<Review>>,
  'listArticles' : ActorMethod<[bigint, bigint], ArticlePage>,
  'listLeads' : ActorMethod<[], Array<Lead>>,
  'listProperties' : ActorMethod<[PropertyFilters], PropertyPage>,
  'listReviewsByProperty' : ActorMethod<[PropertyId], Array<Review>>,
  'markLeadRead' : ActorMethod<[LeadId], boolean>,
  'submitLead' : ActorMethod<[LeadInput], Lead>,
  'submitReview' : ActorMethod<[ReviewInput], Review>,
  'toggleFeatured' : ActorMethod<[PropertyId], boolean>,
  'updateArticle' : ActorMethod<[ArticleId, ArticleInput], [] | [Article]>,
  'updateProperty' : ActorMethod<[PropertyId, PropertyInput], [] | [Property]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];