/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export type LeadId = string;
export type Slug = string;
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface LeadInput {
    inquiryType: InquiryType;
    name: string;
    propertyTitle?: string;
    propertyId?: PropertyId;
    email: string;
    message: string;
    phone: string;
}
export type ArticleId = string;
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface PropertyInput {
    galleryImages: Array<ExternalBlob>;
    status: PropertyStatus;
    title: string;
    propertyType: PropertyType;
    bedrooms: bigint;
    city: string;
    overview: string;
    slug: Slug;
    description: string;
    amenities: Array<string>;
    heroImage: ExternalBlob;
    isFeatured: boolean;
    address: string;
    areaSqft: number;
    bathrooms: bigint;
    price: number;
    floorplans: Array<ExternalBlob>;
}
export interface Property {
    id: PropertyId;
    galleryImages: Array<ExternalBlob>;
    status: PropertyStatus;
    title: string;
    propertyType: PropertyType;
    bedrooms: bigint;
    city: string;
    createdAt: Timestamp;
    overview: string;
    slug: Slug;
    description: string;
    amenities: Array<string>;
    heroImage: ExternalBlob;
    updatedAt: Timestamp;
    isFeatured: boolean;
    address: string;
    areaSqft: number;
    bathrooms: bigint;
    price: number;
    floorplans: Array<ExternalBlob>;
}
export interface Lead {
    id: LeadId;
    inquiryType: InquiryType;
    name: string;
    createdAt: Timestamp;
    propertyTitle?: string;
    propertyId?: PropertyId;
    isRead: boolean;
    email: string;
    message: string;
    phone: string;
}
export interface PropertyPage {
    total: bigint;
    offset: bigint;
    limit: bigint;
    items: Array<Property>;
}
export type PropertyId = string;
export interface ArticlePage {
    total: bigint;
    offset: bigint;
    limit: bigint;
    items: Array<Article>;
}
export interface ArticleInput {
    metaDescription: string;
    title: string;
    content: string;
    isPublished: boolean;
    featuredImage: ExternalBlob;
    slug: Slug;
    author: string;
}
export type ReviewId = string;
export interface PropertyFilters {
    propertyType?: PropertyType;
    offset: bigint;
    minBedrooms?: bigint;
    limit: bigint;
    searchTerm?: string;
    priceMax?: number;
    priceMin?: number;
}
export interface ReviewInput {
    name: string;
    propertyId: PropertyId;
    email: string;
    comment: string;
    rating: bigint;
}
export interface Review {
    id: ReviewId;
    isApproved: boolean;
    name: string;
    createdAt: Timestamp;
    propertyId: PropertyId;
    email: string;
    comment: string;
    rating: bigint;
}
export interface Article {
    id: ArticleId;
    metaDescription: string;
    title: string;
    content: string;
    isPublished: boolean;
    featuredImage: ExternalBlob;
    slug: Slug;
    publishedAt: Timestamp;
    author: string;
    updatedAt: Timestamp;
}
export enum InquiryType {
    offer = "offer",
    information = "information",
    general = "general",
    viewingRequest = "viewingRequest"
}
export enum PropertyStatus {
    active = "active",
    pending = "pending",
    sold = "sold",
    inactive = "inactive"
}
export enum PropertyType {
    rental = "rental",
    resale = "resale",
    newProject = "newProject",
    sale = "sale",
    plotLand = "plotLand"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    approveReview(id: ReviewId): Promise<boolean>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createArticle(input: ArticleInput): Promise<Article>;
    createProperty(input: PropertyInput): Promise<Property>;
    deleteArticle(id: ArticleId): Promise<boolean>;
    deleteLead(id: LeadId): Promise<boolean>;
    deleteProperty(id: PropertyId): Promise<boolean>;
    deleteReview(id: ReviewId): Promise<boolean>;
    getArticle(id: ArticleId): Promise<Article | null>;
    getArticleBySlug(slug: Slug): Promise<Article | null>;
    getCallerUserRole(): Promise<UserRole>;
    getFeaturedProperties(): Promise<Array<Property>>;
    getProperty(id: PropertyId): Promise<Property | null>;
    getPropertyAverageRating(propertyId: PropertyId): Promise<number>;
    getPropertyBySlug(slug: Slug): Promise<Property | null>;
    getRecentArticles(count: bigint): Promise<Array<Article>>;
    isCallerAdmin(): Promise<boolean>;
    listAllReviews(): Promise<Array<Review>>;
    listArticles(offset: bigint, limit: bigint): Promise<ArticlePage>;
    listLeads(): Promise<Array<Lead>>;
    listProperties(filters: PropertyFilters): Promise<PropertyPage>;
    listReviewsByProperty(propertyId: PropertyId): Promise<Array<Review>>;
    markLeadRead(id: LeadId): Promise<boolean>;
    submitLead(input: LeadInput): Promise<Lead>;
    submitReview(input: ReviewInput): Promise<Review>;
    toggleFeatured(id: PropertyId): Promise<boolean>;
    updateArticle(id: ArticleId, input: ArticleInput): Promise<Article | null>;
    updateProperty(id: PropertyId, input: PropertyInput): Promise<Property | null>;
}
import type { Article as _Article, ArticleId as _ArticleId, ArticleInput as _ArticleInput, ArticlePage as _ArticlePage, ExternalBlob as _ExternalBlob, InquiryType as _InquiryType, Lead as _Lead, LeadId as _LeadId, LeadInput as _LeadInput, Property as _Property, PropertyFilters as _PropertyFilters, PropertyId as _PropertyId, PropertyInput as _PropertyInput, PropertyPage as _PropertyPage, PropertyStatus as _PropertyStatus, PropertyType as _PropertyType, Slug as _Slug, Timestamp as _Timestamp, UserRole as _UserRole, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async approveReview(arg0: ReviewId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.approveReview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveReview(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createArticle(arg0: ArticleInput): Promise<Article> {
        if (this.processError) {
            try {
                const result = await this.actor.createArticle(await to_candid_ArticleInput_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Article_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createArticle(await to_candid_ArticleInput_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Article_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async createProperty(arg0: PropertyInput): Promise<Property> {
        if (this.processError) {
            try {
                const result = await this.actor.createProperty(await to_candid_PropertyInput_n16(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Property_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProperty(await to_candid_PropertyInput_n16(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Property_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteArticle(arg0: ArticleId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteArticle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteArticle(arg0);
            return result;
        }
    }
    async deleteLead(arg0: LeadId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLead(arg0);
            return result;
        }
    }
    async deleteProperty(arg0: PropertyId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProperty(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProperty(arg0);
            return result;
        }
    }
    async deleteReview(arg0: ReviewId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteReview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteReview(arg0);
            return result;
        }
    }
    async getArticle(arg0: ArticleId): Promise<Article | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getArticle(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArticle(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getArticleBySlug(arg0: Slug): Promise<Article | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getArticleBySlug(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArticleBySlug(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeaturedProperties(): Promise<Array<Property>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeaturedProperties();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeaturedProperties();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProperty(arg0: PropertyId): Promise<Property | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProperty(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProperty(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPropertyAverageRating(arg0: PropertyId): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getPropertyAverageRating(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPropertyAverageRating(arg0);
            return result;
        }
    }
    async getPropertyBySlug(arg0: Slug): Promise<Property | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPropertyBySlug(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPropertyBySlug(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecentArticles(arg0: bigint): Promise<Array<Article>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecentArticles(arg0);
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecentArticles(arg0);
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAllReviews(): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllReviews();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllReviews();
            return result;
        }
    }
    async listArticles(arg0: bigint, arg1: bigint): Promise<ArticlePage> {
        if (this.processError) {
            try {
                const result = await this.actor.listArticles(arg0, arg1);
                return from_candid_ArticlePage_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listArticles(arg0, arg1);
            return from_candid_ArticlePage_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async listLeads(): Promise<Array<Lead>> {
        if (this.processError) {
            try {
                const result = await this.actor.listLeads();
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listLeads();
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async listProperties(arg0: PropertyFilters): Promise<PropertyPage> {
        if (this.processError) {
            try {
                const result = await this.actor.listProperties(to_candid_PropertyFilters_n45(this._uploadFile, this._downloadFile, arg0));
                return from_candid_PropertyPage_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProperties(to_candid_PropertyFilters_n45(this._uploadFile, this._downloadFile, arg0));
            return from_candid_PropertyPage_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async listReviewsByProperty(arg0: PropertyId): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.listReviewsByProperty(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listReviewsByProperty(arg0);
            return result;
        }
    }
    async markLeadRead(arg0: LeadId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.markLeadRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markLeadRead(arg0);
            return result;
        }
    }
    async submitLead(arg0: LeadInput): Promise<Lead> {
        if (this.processError) {
            try {
                const result = await this.actor.submitLead(to_candid_LeadInput_n49(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Lead_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitLead(to_candid_LeadInput_n49(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Lead_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitReview(arg0: ReviewInput): Promise<Review> {
        if (this.processError) {
            try {
                const result = await this.actor.submitReview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitReview(arg0);
            return result;
        }
    }
    async toggleFeatured(arg0: PropertyId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleFeatured(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleFeatured(arg0);
            return result;
        }
    }
    async updateArticle(arg0: ArticleId, arg1: ArticleInput): Promise<Article | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateArticle(arg0, await to_candid_ArticleInput_n10(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateArticle(arg0, await to_candid_ArticleInput_n10(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProperty(arg0: PropertyId, arg1: PropertyInput): Promise<Property | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProperty(arg0, await to_candid_PropertyInput_n16(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProperty(arg0, await to_candid_PropertyInput_n16(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
}
async function from_candid_ArticlePage_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ArticlePage): Promise<ArticlePage> {
    return await from_candid_record_n37(_uploadFile, _downloadFile, value);
}
async function from_candid_Article_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Article): Promise<Article> {
    return await from_candid_record_n14(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_InquiryType_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InquiryType): InquiryType {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid_Lead_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Lead): Lead {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
async function from_candid_PropertyPage_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PropertyPage): Promise<PropertyPage> {
    return await from_candid_record_n48(_uploadFile, _downloadFile, value);
}
function from_candid_PropertyStatus_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PropertyStatus): PropertyStatus {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_PropertyType_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PropertyType): PropertyType {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
async function from_candid_Property_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Property): Promise<Property> {
    return await from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Article]): Promise<Article | null> {
    return value.length === 0 ? null : await from_candid_Article_n13(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Property]): Promise<Property | null> {
    return value.length === 0 ? null : await from_candid_Property_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PropertyId]): PropertyId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ArticleId;
    metaDescription: string;
    title: string;
    content: string;
    isPublished: boolean;
    featuredImage: _ExternalBlob;
    slug: _Slug;
    publishedAt: _Timestamp;
    author: string;
    updatedAt: _Timestamp;
}): Promise<{
    id: ArticleId;
    metaDescription: string;
    title: string;
    content: string;
    isPublished: boolean;
    featuredImage: ExternalBlob;
    slug: Slug;
    publishedAt: Timestamp;
    author: string;
    updatedAt: Timestamp;
}> {
    return {
        id: value.id,
        metaDescription: value.metaDescription,
        title: value.title,
        content: value.content,
        isPublished: value.isPublished,
        featuredImage: await from_candid_ExternalBlob_n15(_uploadFile, _downloadFile, value.featuredImage),
        slug: value.slug,
        publishedAt: value.publishedAt,
        author: value.author,
        updatedAt: value.updatedAt
    };
}
async function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PropertyId;
    galleryImages: Array<_ExternalBlob>;
    status: _PropertyStatus;
    title: string;
    propertyType: _PropertyType;
    bedrooms: bigint;
    city: string;
    createdAt: _Timestamp;
    overview: string;
    slug: _Slug;
    description: string;
    amenities: Array<string>;
    heroImage: _ExternalBlob;
    updatedAt: _Timestamp;
    isFeatured: boolean;
    address: string;
    areaSqft: number;
    bathrooms: bigint;
    price: number;
    floorplans: Array<_ExternalBlob>;
}): Promise<{
    id: PropertyId;
    galleryImages: Array<ExternalBlob>;
    status: PropertyStatus;
    title: string;
    propertyType: PropertyType;
    bedrooms: bigint;
    city: string;
    createdAt: Timestamp;
    overview: string;
    slug: Slug;
    description: string;
    amenities: Array<string>;
    heroImage: ExternalBlob;
    updatedAt: Timestamp;
    isFeatured: boolean;
    address: string;
    areaSqft: number;
    bathrooms: bigint;
    price: number;
    floorplans: Array<ExternalBlob>;
}> {
    return {
        id: value.id,
        galleryImages: await from_candid_vec_n25(_uploadFile, _downloadFile, value.galleryImages),
        status: from_candid_PropertyStatus_n26(_uploadFile, _downloadFile, value.status),
        title: value.title,
        propertyType: from_candid_PropertyType_n28(_uploadFile, _downloadFile, value.propertyType),
        bedrooms: value.bedrooms,
        city: value.city,
        createdAt: value.createdAt,
        overview: value.overview,
        slug: value.slug,
        description: value.description,
        amenities: value.amenities,
        heroImage: await from_candid_ExternalBlob_n15(_uploadFile, _downloadFile, value.heroImage),
        updatedAt: value.updatedAt,
        isFeatured: value.isFeatured,
        address: value.address,
        areaSqft: value.areaSqft,
        bathrooms: value.bathrooms,
        price: value.price,
        floorplans: await from_candid_vec_n25(_uploadFile, _downloadFile, value.floorplans)
    };
}
async function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total: bigint;
    offset: bigint;
    limit: bigint;
    items: Array<_Article>;
}): Promise<{
    total: bigint;
    offset: bigint;
    limit: bigint;
    items: Array<Article>;
}> {
    return {
        total: value.total,
        offset: value.offset,
        limit: value.limit,
        items: await from_candid_vec_n35(_uploadFile, _downloadFile, value.items)
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _LeadId;
    inquiryType: _InquiryType;
    name: string;
    createdAt: _Timestamp;
    propertyTitle: [] | [string];
    propertyId: [] | [_PropertyId];
    isRead: boolean;
    email: string;
    message: string;
    phone: string;
}): {
    id: LeadId;
    inquiryType: InquiryType;
    name: string;
    createdAt: Timestamp;
    propertyTitle?: string;
    propertyId?: PropertyId;
    isRead: boolean;
    email: string;
    message: string;
    phone: string;
} {
    return {
        id: value.id,
        inquiryType: from_candid_InquiryType_n41(_uploadFile, _downloadFile, value.inquiryType),
        name: value.name,
        createdAt: value.createdAt,
        propertyTitle: record_opt_to_undefined(from_candid_opt_n43(_uploadFile, _downloadFile, value.propertyTitle)),
        propertyId: record_opt_to_undefined(from_candid_opt_n44(_uploadFile, _downloadFile, value.propertyId)),
        isRead: value.isRead,
        email: value.email,
        message: value.message,
        phone: value.phone
    };
}
async function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total: bigint;
    offset: bigint;
    limit: bigint;
    items: Array<_Property>;
}): Promise<{
    total: bigint;
    offset: bigint;
    limit: bigint;
    items: Array<Property>;
}> {
    return {
        total: value.total,
        offset: value.offset,
        limit: value.limit,
        items: await from_candid_vec_n33(_uploadFile, _downloadFile, value.items)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    pending: null;
} | {
    sold: null;
} | {
    inactive: null;
}): PropertyStatus {
    return "active" in value ? PropertyStatus.active : "pending" in value ? PropertyStatus.pending : "sold" in value ? PropertyStatus.sold : "inactive" in value ? PropertyStatus.inactive : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    rental: null;
} | {
    resale: null;
} | {
    newProject: null;
} | {
    sale: null;
} | {
    plotLand: null;
}): PropertyType {
    return "rental" in value ? PropertyType.rental : "resale" in value ? PropertyType.resale : "newProject" in value ? PropertyType.newProject : "sale" in value ? PropertyType.sale : "plotLand" in value ? PropertyType.plotLand : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    offer: null;
} | {
    information: null;
} | {
    general: null;
} | {
    viewingRequest: null;
}): InquiryType {
    return "offer" in value ? InquiryType.offer : "information" in value ? InquiryType.information : "general" in value ? InquiryType.general : "viewingRequest" in value ? InquiryType.viewingRequest : value;
}
async function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n15(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Property>): Promise<Array<Property>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Property_n23(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Article>): Promise<Array<Article>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Article_n13(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Lead>): Array<Lead> {
    return value.map((x)=>from_candid_Lead_n39(_uploadFile, _downloadFile, x));
}
async function to_candid_ArticleInput_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ArticleInput): Promise<_ArticleInput> {
    return await to_candid_record_n11(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_InquiryType_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InquiryType): _InquiryType {
    return to_candid_variant_n52(_uploadFile, _downloadFile, value);
}
function to_candid_LeadInput_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeadInput): _LeadInput {
    return to_candid_record_n50(_uploadFile, _downloadFile, value);
}
function to_candid_PropertyFilters_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyFilters): _PropertyFilters {
    return to_candid_record_n46(_uploadFile, _downloadFile, value);
}
async function to_candid_PropertyInput_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyInput): Promise<_PropertyInput> {
    return await to_candid_record_n17(_uploadFile, _downloadFile, value);
}
function to_candid_PropertyStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyStatus): _PropertyStatus {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_PropertyType_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyType): _PropertyType {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    metaDescription: string;
    title: string;
    content: string;
    isPublished: boolean;
    featuredImage: ExternalBlob;
    slug: Slug;
    author: string;
}): Promise<{
    metaDescription: string;
    title: string;
    content: string;
    isPublished: boolean;
    featuredImage: _ExternalBlob;
    slug: _Slug;
    author: string;
}> {
    return {
        metaDescription: value.metaDescription,
        title: value.title,
        content: value.content,
        isPublished: value.isPublished,
        featuredImage: await to_candid_ExternalBlob_n12(_uploadFile, _downloadFile, value.featuredImage),
        slug: value.slug,
        author: value.author
    };
}
async function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    galleryImages: Array<ExternalBlob>;
    status: PropertyStatus;
    title: string;
    propertyType: PropertyType;
    bedrooms: bigint;
    city: string;
    overview: string;
    slug: Slug;
    description: string;
    amenities: Array<string>;
    heroImage: ExternalBlob;
    isFeatured: boolean;
    address: string;
    areaSqft: number;
    bathrooms: bigint;
    price: number;
    floorplans: Array<ExternalBlob>;
}): Promise<{
    galleryImages: Array<_ExternalBlob>;
    status: _PropertyStatus;
    title: string;
    propertyType: _PropertyType;
    bedrooms: bigint;
    city: string;
    overview: string;
    slug: _Slug;
    description: string;
    amenities: Array<string>;
    heroImage: _ExternalBlob;
    isFeatured: boolean;
    address: string;
    areaSqft: number;
    bathrooms: bigint;
    price: number;
    floorplans: Array<_ExternalBlob>;
}> {
    return {
        galleryImages: await to_candid_vec_n18(_uploadFile, _downloadFile, value.galleryImages),
        status: to_candid_PropertyStatus_n19(_uploadFile, _downloadFile, value.status),
        title: value.title,
        propertyType: to_candid_PropertyType_n21(_uploadFile, _downloadFile, value.propertyType),
        bedrooms: value.bedrooms,
        city: value.city,
        overview: value.overview,
        slug: value.slug,
        description: value.description,
        amenities: value.amenities,
        heroImage: await to_candid_ExternalBlob_n12(_uploadFile, _downloadFile, value.heroImage),
        isFeatured: value.isFeatured,
        address: value.address,
        areaSqft: value.areaSqft,
        bathrooms: value.bathrooms,
        price: value.price,
        floorplans: await to_candid_vec_n18(_uploadFile, _downloadFile, value.floorplans)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    propertyType?: PropertyType;
    offset: bigint;
    minBedrooms?: bigint;
    limit: bigint;
    searchTerm?: string;
    priceMax?: number;
    priceMin?: number;
}): {
    propertyType: [] | [_PropertyType];
    offset: bigint;
    minBedrooms: [] | [bigint];
    limit: bigint;
    searchTerm: [] | [string];
    priceMax: [] | [number];
    priceMin: [] | [number];
} {
    return {
        propertyType: value.propertyType ? candid_some(to_candid_PropertyType_n21(_uploadFile, _downloadFile, value.propertyType)) : candid_none(),
        offset: value.offset,
        minBedrooms: value.minBedrooms ? candid_some(value.minBedrooms) : candid_none(),
        limit: value.limit,
        searchTerm: value.searchTerm ? candid_some(value.searchTerm) : candid_none(),
        priceMax: value.priceMax ? candid_some(value.priceMax) : candid_none(),
        priceMin: value.priceMin ? candid_some(value.priceMin) : candid_none()
    };
}
function to_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    inquiryType: InquiryType;
    name: string;
    propertyTitle?: string;
    propertyId?: PropertyId;
    email: string;
    message: string;
    phone: string;
}): {
    inquiryType: _InquiryType;
    name: string;
    propertyTitle: [] | [string];
    propertyId: [] | [_PropertyId];
    email: string;
    message: string;
    phone: string;
} {
    return {
        inquiryType: to_candid_InquiryType_n51(_uploadFile, _downloadFile, value.inquiryType),
        name: value.name,
        propertyTitle: value.propertyTitle ? candid_some(value.propertyTitle) : candid_none(),
        propertyId: value.propertyId ? candid_some(value.propertyId) : candid_none(),
        email: value.email,
        message: value.message,
        phone: value.phone
    };
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyStatus): {
    active: null;
} | {
    pending: null;
} | {
    sold: null;
} | {
    inactive: null;
} {
    return value == PropertyStatus.active ? {
        active: null
    } : value == PropertyStatus.pending ? {
        pending: null
    } : value == PropertyStatus.sold ? {
        sold: null
    } : value == PropertyStatus.inactive ? {
        inactive: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyType): {
    rental: null;
} | {
    resale: null;
} | {
    newProject: null;
} | {
    sale: null;
} | {
    plotLand: null;
} {
    return value == PropertyType.rental ? {
        rental: null
    } : value == PropertyType.resale ? {
        resale: null
    } : value == PropertyType.newProject ? {
        newProject: null
    } : value == PropertyType.sale ? {
        sale: null
    } : value == PropertyType.plotLand ? {
        plotLand: null
    } : value;
}
function to_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InquiryType): {
    offer: null;
} | {
    information: null;
} | {
    general: null;
} | {
    viewingRequest: null;
} {
    return value == InquiryType.offer ? {
        offer: null
    } : value == InquiryType.information ? {
        information: null
    } : value == InquiryType.general ? {
        general: null
    } : value == InquiryType.viewingRequest ? {
        viewingRequest: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
async function to_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n12(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
